In [2]:
import sys
sys.path.append("../")

import pandas as pd
import seaborn as sns
import numpy as np

sns.set_style('darkgrid')
sns.set(font_scale = 1.5)

In [3]:
from src.finman.utils.gsheet import GSheetWorker

In [4]:
sheet_id = "1GqwNPuOtQUXfltK6F4oHpx-U1BqBgiDZfC5YfDcJyto"
gcreds_file = "../secrets/finman-433017-da308d823497.json"

gsw = GSheetWorker(gcreds_file)

# 1. Data Processing

### 1.1 Чтение всех транзакций из гуглодока

In [5]:
sheet_setups = [
    {
        "bank_sheet_name": "t-bank (main)",
        "dt_col": "Время операции",
        "trans_rub_col": "Сумма операции в валюте карты",
        "desc_col": "Описание операции",
    },
    {
        "bank_sheet_name": "t-bank (deposit)",
        "dt_col": "Время операции",
        "trans_rub_col": "Сумма операции в валюте карты",
        "desc_col": "Описание операции",
    },
    {
        "bank_sheet_name": "t-bank (invest)",
        "dt_col": "Время операции",
        "trans_rub_col": "Сумма операции в валюте карты",
        "desc_col": "Описание операции",
    },
    {
        "bank_sheet_name": "ozon-bank (main)",
        "dt_col": "Время операции",
        "trans_rub_col": "Сумма операции",
        "desc_col": "Назначение платежа",
    },
    {
        "bank_sheet_name": "сбер (main)",
        "dt_col": "Время операции",
        "trans_rub_col": "Сумма в валюте счета",
        "desc_col": "Описание",
    }
]

transaction_lists = [
    "t-bank (main)", 
    "ozon-bank (main)",
    "сбер (main)"
]


cat_col = "Категория"
subcat_col = "Подкатегория"
debt_col = "Долг"

In [46]:
trans_df = []
for setup in sheet_setups:
    gs_df = gsw.get_df(sheet_id, setup["bank_sheet_name"])

    gs_df = gs_df.rename(columns={
        setup['dt_col']: "dt",
        setup['trans_rub_col']: "trans_rub",
        setup['desc_col']: "description",

    })

    if setup["bank_sheet_name"] in transaction_lists:
        trans_df.append(gs_df[[
            "id", "dt", "trans_rub", "description", cat_col, subcat_col, debt_col
        ]])
    else:
        trans_df.append(gs_df[[
            "dt", "trans_rub", cat_col, subcat_col
        ]])

    trans_df[-1]['account'] = setup["bank_sheet_name"]

    print(setup["bank_sheet_name"] + " done!")

trans_df = pd.concat(trans_df)

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_71827/943269463.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trans_df[-1]['account'] = setup["bank_sheet_name"]

t-bank (main) done!

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_71827/943269463.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trans_df[-1]['account'] = setup["bank_sheet_name"]

t-bank (deposit) done!

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_71827/943269463.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trans_df[-1]['account'] = setup["bank_sheet_name"]

t-bank (invest) done!

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_71827/943269463.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trans_df[-1]['account'] = setup["bank_sheet_name"]

ozon-bank (main) done!
сбер (main) done!

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_71827/943269463.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trans_df[-1]['account'] = setup["bank_sheet_name"]

In [47]:
trans_df.head()

,id,dt,trans_rub,description,Категория,Подкатегория,Долг,account
0,701a707742,2024-10-30 20:27,-4000,Перевод на карту другого банка,Transfer,Internal,None,t-bank (main)
1,675c171212,2024-10-30 12:57,-2283.1,Оплата в Yandex.Lavka Moskva RUS,Food & Dining,Delivery,None,t-bank (main)
2,2ef6d9a28b,2024-10-30 11:39,-2730,Оплата в EGGSELLENT MOSKVA RUS,Entertainment,Restaurants,None,t-bank (main)
3,dd282173e5,2024-10-29 21:53,-900,Внутренний перевод на договор,Entertainment,Restaurants,None,t-bank (main)
4,dcb8f77afa,2024-10-29 20:49,-50,Внутренний перевод на договор,Sport,Padel,None,t-bank (main)

In [48]:
trans_df['dt'] = pd.to_datetime(trans_df['dt'])
trans_df['trans_rub'] = pd.to_numeric(trans_df['trans_rub'])

In [49]:
trans_df.shape

(1881, 8)

In [50]:
print(trans_df.head(5).to_markdown())

|    | id         | dt                  |   trans_rub | description                      | Категория     | Подкатегория   | Долг   | account       |
|---:|:-----------|:--------------------|------------:|:---------------------------------|:--------------|:---------------|:-------|:--------------|
|  0 | 701a707742 | 2024-10-30 20:27:00 |     -4000   | Перевод на карту другого банка   | Transfer      | Internal       |        | t-bank (main) |
|  1 | 675c171212 | 2024-10-30 12:57:00 |     -2283.1 | Оплата в Yandex.Lavka Moskva RUS | Food & Dining | Delivery       |        | t-bank (main) |
|  2 | 2ef6d9a28b | 2024-10-30 11:39:00 |     -2730   | Оплата в EGGSELLENT MOSKVA RUS   | Entertainment | Restaurants    |        | t-bank (main) |
|  3 | dd282173e5 | 2024-10-29 21:53:00 |      -900   | Внутренний перевод на договор    | Entertainment | Restaurants    |        | t-bank (main) |
|  4 | dcb8f77afa | 2024-10-29 20:49:00 |       -50   | Внутренний перевод на договор    | Sport         | Padel          |        | t-bank (main) |

In [51]:
export_df = trans_df.rename(columns={
    "dt": "DATE",
    "trans_rub": "AMOUNT",
    "Категория": "CATEGORY",
    "Подкатегория": "SUBCATEGORY",
    "account": "SOURCE",
    "description": "DESCRIPTION"
}).head(10)

export_df['AMOUNT'] = (export_df['AMOUNT'] * np.random.random(export_df.shape[0])).round()
export_df['DATE'] = export_df['DATE'].dt.strftime("%Y-%m-%d")

# export_df.to_excel("../tmp/Sample Export.xlsx")

In [52]:
export_df.head()

,id,DATE,AMOUNT,DESCRIPTION,CATEGORY,SUBCATEGORY,Долг,SOURCE
0,701a707742,2024-10-30,-1916.0,Перевод на карту другого банка,Transfer,Internal,None,t-bank (main)
1,675c171212,2024-10-30,-1616.0,Оплата в Yandex.Lavka Moskva RUS,Food & Dining,Delivery,None,t-bank (main)
2,2ef6d9a28b,2024-10-30,-1676.0,Оплата в EGGSELLENT MOSKVA RUS,Entertainment,Restaurants,None,t-bank (main)
3,dd282173e5,2024-10-29,-367.0,Внутренний перевод на договор,Entertainment,Restaurants,None,t-bank (main)
4,dcb8f77afa,2024-10-29,-38.0,Внутренний перевод на договор,Sport,Padel,None,t-bank (main)

### 1.2 Агрегация по долгам

In [74]:
trans_df

,id,dt,trans_rub,description,Категория,Подкатегория,Долг,account
0,701a707742,2024-10-30 20:27:00,-4000.0,Перевод на карту другого банка,Transfer,Internal,None,t-bank (main)
1,675c171212,2024-10-30 12:57:00,-2283.1,Оплата в Yandex.Lavka Moskva RUS,Food & Dining,Delivery,None,t-bank (main)
2,2ef6d9a28b,2024-10-30 11:39:00,-2730.0,Оплата в EGGSELLENT MOSKVA RUS,Entertainment,Restaurants,None,t-bank (main)
3,dd282173e5,2024-10-29 21:53:00,-900.0,Внутренний перевод на договор,Entertainment,Restaurants,None,t-bank (main)
4,dcb8f77afa,2024-10-29 20:49:00,-50.0,Внутренний перевод на договор,Sport,Padel,None,t-bank (main)
...,...,...,...,...,...,...,...,...
29,62ea4b79b1,2024-07-08 17:51:00,-20000.0,Перевод с карты. 08.07.2024 SBOL перевод на ка...,None,None,None,сбер (main)
30,10abb199cd,2024-07-07 11:10:00,18100.0,Перевод на карту. 07.07.2024 SBOL перевод с ка...,None,None,None,сбер (main)
31,a9fdfadcfe,2024-07-04 10:49:00,3000.0,Перевод на карту. 04.07.2024 SBOL перевод с ка...,None,None,None,сбер (main)
32,347bdfa073,2024-07-02 21:06:00,-150.0,Перевод с карты. 02.07.2024 SBOL перевод на пл...,None,None,None,сбер (main)
33,2c4d3d901e,2024-07-01 14:41:00,-1500.0,Перевод с карты. 01.07.2024 SBOL перевод на ка...,None,None,None,сбер (main)

In [75]:
trans_df_no_debt = trans_df.loc[(trans_df['Долг'].isnull()) | (trans_df['Долг'] == '') | (trans_df['Долг'] == ' ')]
trans_df_debt = trans_df.loc[(trans_df['Долг'] != '') & (trans_df['Долг'].notnull()) & (trans_df['Долг'] != ' ')]

assert (trans_df_no_debt.shape[0] + trans_df_debt.shape[0]) == trans_df.shape[0]

In [76]:
trans_df_debt.sort_values(['Долг', 'dt'], ascending=False).head(10)

,id,dt,trans_rub,description,Категория,Подкатегория,Долг,account
10,8953551b8a,2024-09-06 21:20:00,50000.0,Перевод на карту. 06.09.2024 SBOL перевод с ка...,Transfer,Debt,хата сент 24,сбер (main)
331,2a59e8f587,2024-09-02 10:04:00,-120000.0,Внешний перевод по номеру телефона +79104528167,Household,Mortgage/Rent,хата сент 24,t-bank (main)
113,723cd591c1,2024-10-10 19:36:00,300.0,Внутрибанковский перевод с договора,Transfer,Debt,рестик_241010,t-bank (main)
114,723cd591c1,2024-10-10 19:36:00,300.0,Внутрибанковский перевод с договора,Transfer,Debt,рестик_241010,t-bank (main)
115,6c0261ada6,2024-10-10 19:36:00,300.0,Внутрибанковский перевод с договора,Transfer,Debt,рестик_241010,t-bank (main)
116,723cd591c1,2024-10-10 19:36:00,300.0,Внутрибанковский перевод с договора,Transfer,Debt,рестик_241010,t-bank (main)
117,8f5a8e9e62,2024-10-10 19:34:00,-1500.0,Внешний перевод по номеру телефона +79160945835,Entertainment,Restaurants,рестик_241010,t-bank (main)
2,3af4e02669,2024-10-13 17:47:00,1800.0,Перевод на карту. 13.10.2024 SBOL перевод с ка...,Transfer,Debt,рестик после науки 0+,сбер (main)
92,33f195144d,2024-10-13 17:46:00,-3895.0,Оплата в BATONY KAFE Gorod Moskva RUS,Entertainment,Restaurants,рестик после науки 0+,t-bank (main)
227,7241fce317,2024-09-19 21:59:00,9000.0,Внутрибанковский перевод с договора,Transfer,Debt,раки_240919,t-bank (main)

In [77]:
trans_df_debt = trans_df_debt.groupby('Долг').agg({
    'id': "last",
    'dt': min,
    'trans_rub': sum,
    'Категория': "last",
    'Подкатегория': "last",
    'account': lambda x: ";".join(set(x))
}).reset_index()

In [78]:
trans_df_debt.sort_values('dt', ascending=False)

,Долг,id,dt,trans_rub,Категория,Подкатегория,account
9,падел_241022,587eca4dba,2024-10-22 11:14:00,-3400.0,Sport,Padel,t-bank (main)
5,мак к зубрам,8448b21b69,2024-10-19 13:54:00,-274.0,Transfer,Debt,t-bank (main);сбер (main)
3,костюм в яки,182bc95398,2024-10-15 17:58:00,-12500.0,Other,Other,t-bank (main)
12,рестик после науки 0+,3af4e02669,2024-10-13 17:46:00,-2095.0,Transfer,Debt,t-bank (main);сбер (main)
13,рестик_241010,8f5a8e9e62,2024-10-10 19:34:00,-300.0,Entertainment,Restaurants,t-bank (main)
8,падел_241004,168e4c4298,2024-10-04 15:46:00,-800.0,Sport,Padel,t-bank (main)
1,egg_s 240925,8abd2da1a0,2024-09-25 11:03:00,-1540.0,Entertainment,Restaurants,t-bank (main)
11,раки_240919,d897f9d6d2,2024-09-19 21:55:00,-5480.0,Entertainment,Restaurants,t-bank (main)
4,кэш_алене 240913,5364f56ddd,2024-09-13 20:06:00,0.0,Transfer,Debt,t-bank (main)
2,др мамы 24,78c24027f8,2024-09-06 13:55:00,-18586.0,Transfer,Debt,t-bank (main);сбер (main)
14,хата сент 24,8953551b8a,2024-09-02 10:04:00,-70000.0,Transfer,Debt,t-bank (main);сбер (main)
0,Padel_240903,2a7f3082d8,2024-08-28 10:55:00,-1500.0,Sport,Padel,t-bank (main)
7,падел240816,483efaf0ef,2024-08-13 11:29:00,-6000.0,Sport,Padel,t-bank (main)
6,падел фили 240807,ae57a34c7f,2024-08-05 17:02:00,-2975.0,Sport,Padel,t-bank (main)
10,подарок на годовщину2024,ee64b2a631,2024-07-21 16:21:00,15000.0,Debt,Other,t-bank (main)

In [79]:
trans_df_debt_free = pd.concat((trans_df_debt, trans_df_no_debt))

### 1.3 Фильтруем только транзакции для отчета

In [172]:
exp_mask = (trans_df_debt_free['trans_rub'] < 0) & (trans_df_debt_free['account'].isin(transaction_lists) & \
                                                    (trans_df_debt_free['Категория'] != "Transfer") & \
                                                    (trans_df_debt_free['Подкатегория'] != "Internal"))
inc_mask = (trans_df_debt_free['trans_rub'] > 0)

exp_df = trans_df_debt_free.loc[exp_mask]
exp_df['trans_rub'] = exp_df['trans_rub'].abs()

/var/folders/n9/7qzl9sfj3_n9hmnht95_9jy80000gn/T/ipykernel_3547/2815616887.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [173]:
months_dict = {key: value for key,value in zip(np.arange(1, 13), ["январь", "февраль", "март", "апрель", "май", "июнь", 
                                                                    "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"])}

In [174]:
months_dict

{1: 'январь',
 2: 'февраль',
 3: 'март',
 4: 'апрель',
 5: 'май',
 6: 'июнь',
 7: 'июль',
 8: 'август',
 9: 'сентябрь',
 10: 'октябрь',
 11: 'ноябрь',
 12: 'декабрь'}

# График трат по категориям

In [175]:
month = 9

In [176]:
df_vis = exp_df.loc[exp_df['dt'].dt.month == month]

In [179]:
df_vis

,Долг,dt,trans_rub,Категория,Подкатегория,account
1,egg_s 240925,2024-09-25 11:03:00,1540.00,Entertainment,Restaurants,t-bank (main)
2,др мамы 24,2024-09-06 13:55:00,25586.00,Shopping,Gifts,t-bank (main)
11,раки_240919,2024-09-19 21:55:00,5480.00,Entertainment,Restaurants,t-bank (main)
14,хата сент 24,2024-09-02 10:04:00,120000.00,Household,Mortgage/Rent,t-bank (main)
168,None,2024-09-30 23:50:00,362.01,Transportation,Carsharing,t-bank (main)
...,...,...,...,...,...,...
15,None,2024-09-30 17:55:00,1204.00,Household,Accessories,ozon-bank (main)
16,None,2024-09-13 08:08:00,177.00,Household,Accessories,ozon-bank (main)
17,None,2024-09-12 18:37:00,928.00,Household,Accessories,ozon-bank (main)
20,None,2024-09-07 16:29:00,492.00,Shopping,Gifts,ozon-bank (main)
22,None,2024-09-04 21:45:00,4191.00,Household,Accessories,ozon-bank (main)

In [177]:
df_vis

,Долг,dt,trans_rub,Категория,Подкатегория,account
1,egg_s 240925,2024-09-25 11:03:00,1540.00,Entertainment,Restaurants,t-bank (main)
2,др мамы 24,2024-09-06 13:55:00,25586.00,Shopping,Gifts,t-bank (main)
11,раки_240919,2024-09-19 21:55:00,5480.00,Entertainment,Restaurants,t-bank (main)
14,хата сент 24,2024-09-02 10:04:00,120000.00,Household,Mortgage/Rent,t-bank (main)
168,None,2024-09-30 23:50:00,362.01,Transportation,Carsharing,t-bank (main)
...,...,...,...,...,...,...
15,None,2024-09-30 17:55:00,1204.00,Household,Accessories,ozon-bank (main)
16,None,2024-09-13 08:08:00,177.00,Household,Accessories,ozon-bank (main)
17,None,2024-09-12 18:37:00,928.00,Household,Accessories,ozon-bank (main)
20,None,2024-09-07 16:29:00,492.00,Shopping,Gifts,ozon-bank (main)
22,None,2024-09-04 21:45:00,4191.00,Household,Accessories,ozon-bank (main)

In [178]:
import pandas as pd
import plotly.graph_objects as go
from ipywidgets import Output


# Output widget for displaying interactive figures
output = Output()

# Function to generate category waterfall chart
def create_category_waterfall():
    category_data = df_vis.groupby('Категория')['trans_rub'].sum().reset_index()
    
    fig = go.FigureWidget(go.Waterfall(
        x=category_data['Категория'],
        y=category_data['trans_rub'],
        connector=dict(line=dict(color="black", dash="dot"))
    ))

    fig.update_layout(title="Transaction Distribution by Category (Waterfall Chart)")
    
    # Click event for category waterfall
    fig.data[0].on_click(on_category_click)
    with output:
        output.clear_output(wait=True)
        display(fig)

# Function to generate subcategory waterfall chart based on selected category
def create_subcategory_waterfall(selected_category):
    subcategory_data = df_vis[df_vis['Категория'] == selected_category].groupby('Подкатегория')['trans_rub'].sum().reset_index()

    fig = go.FigureWidget(go.Waterfall(
        x=subcategory_data['Подкатегория'],
        y=subcategory_data['trans_rub'],
        connector=dict(line=dict(color="black", dash="dot"))
    ))

    fig.update_layout(title=f"Transaction Distribution in {selected_category} by Subcategory (Waterfall Chart)")
    
    # Click event to go back to main category waterfall
    fig.data[0].on_click(on_subcategory_click)
    with output:
        output.clear_output(wait=True)
        display(fig)

# Event handler when a category bar is clicked
def on_category_click(trace, points, state):
    selected_category = trace.x[points.point_inds[0]]
    create_subcategory_waterfall(selected_category)

# Event handler to go back to category view
def on_subcategory_click(trace, points, state):
    create_category_waterfall()

# Display the initial category waterfall chart
create_category_waterfall()
output

Output()